export const DARK_MODE = 'DARK_MODE';
export const ADD_POKEMON_IN_LIST = 'ADD_POKEMON_IN_LIST';
export const REMOVE_POKEMON_FROM_LIST = 'REMOVE_POKEMON_FROM_LIST';
export const REMOVE_ALL_POKEMONS_FROM_LIST = 'REMOVE_ALL_POKEMONS_FROM_LIST';
